charts/bitcoind/Chart.yaml
charts/bitcoind/charts/prometheus-exporter/templates/deployment.yaml
charts/bitcoind/charts/specter/Chart.yaml
charts/bitcoind/charts/specter/templates/statefulset.yaml
charts/bitcoind/templates/bitcoind-networkpolicy.yaml
charts/bitcoind/templates/dns-networkpolicy.yaml
charts/bitcoind/templates/prometheus-networkpolicy.yaml

this should fix the issue for specter

more testing for network policy

---

charts/bitcoind/templates/configmap.yaml
charts/bitcoind/templates/secrets.yaml
charts/bitcoind/values.yaml

This enables pre-provisioning of a known secret
Related https://github.com/GaloyMoney/charts/issues/44.
Expected to be backwards compatible

Conditionally create secret

---

charts/galoy/Chart.lock
charts/galoy/Chart.yaml

This reverts commit e2c45dd1e97e37731ad947c21c8d6a7fbb20667d.

Revert "Upgrade mongodb chart to 10.29.0"

---

charts/galoy/values.yaml
dev/galoy/galoy-values.yml

By default disable apollo in chart but enable for dev

---

charts/dealer/.helmignore
charts/dealer/Chart.lock
charts/dealer/Chart.yaml
charts/dealer/templates/_helpers.tpl
charts/dealer/templates/dealer-deployment.yaml
charts/dealer/templates/fakegaloyapi-deployment.yaml
charts/dealer/templates/fakegaloyapi-service.yaml
charts/dealer/values.yaml
charts/galoy/charts/lnpay/Chart.yaml
charts/galoy/charts/price/Chart.yaml
charts/lnd/charts/lndmon/Chart.yaml
charts/lnd/charts/loop/Chart.yaml
charts/monitoring/Chart.yaml
charts/rtl/Chart.yaml
dev/addons/dealer.tf
dev/dealer/main.tf
dev/main.tf

Adds the chart to spin up [GaloyMoney/dealer](https://github.com/GaloyMoney/dealer).

Dealer Helm Chart

---

ci/pipeline-fragments.lib.yml
ci/tasks/dealer-smoketest.sh
ci/testflight/dealer/main.tf

Added dealer test flight infra and added it to addons pipeline.

Dealer Testflight

---

charts/dealer/templates/dealer-deployment.yaml
charts/dealer/values.yaml

Fix dealer hedging env

---

ci/tasks/bump-dealer-dashboard.sh

values.yml -> yaml

---

.github/workflows/bot-automerge.yaml

Reference: https://github.com/pascalgn/automerge-action#configuration

Automerge via squash commit

---

charts/galoy/templates/deployment.yaml
charts/galoy/values.yaml
ci/testflight/galoy/main.tf
dev/galoy/main.tf

This contributes towards twilio sub-account infrastructure.
Linked: https://github.com/GaloyMoney/galoy/pull/872

chore: modify galoy chart to use twilio auth token

---

charts/dealer/values.yaml

Revert "bump-dealer-image-bb8dc14"

---

charts/monitoring/values.yaml

Also as an ad hoc cleanup I've removed all the alerting defaults as we are currently relying on honeycomb for alerting.

feat: use new schema for pinging api in monitoring chart

---

charts/lnd/templates/statefulset.yaml
charts/lnd/values.yaml

Could help in regular database compaction

feat: added kubemonkey labels for lnd

---

charts/web-wallet/.helmignore
charts/web-wallet/Chart.yaml
charts/web-wallet/templates/_helpers.tpl
charts/web-wallet/templates/deployment.yaml
charts/web-wallet/templates/ingress.yaml
charts/web-wallet/templates/secrets.yaml
charts/web-wallet/templates/service.yaml
charts/web-wallet/values.yaml
dev/addons/web-wallet.tf

It's unclear at the moment what the ideal prod values will be for web-wallet, so for now I've just kept the values that make it work locally. Once deployed, I will change the values as required to match prod values.

feat: add web wallet chart

---

dev/bitcoin/generateBlock.sh

There's no need to have the script interact with the lnd pod, we can just have it depend upon bitcoind and generate blocks as soon as it's ready.

refactor: simplify block generation script

---

charts/dealer/templates/dealer-price-service.yml
charts/dealer/values.yaml

Adds the dealer price service to dealer templates.
Follow up: Should we inject the URI to this service as an environment variable on galoy?
CC @bodymindarts @krtk6160

feat: add dealer price service

---

ci/pipeline.yml
ci/repipe
ci/tasks/open-update-helm-deps-pr.sh
ci/tasks/update-helm-dep.sh

This PR would create updates to helm dependency using this custom [Helm Concourse Resource](https://github.com/GaloyMoney/helm-concourse-resource)

ci: auto bump helm dependencies

---

charts/lnd/values.yaml

Update log level to improve disk usage performance

perf: update debuglevel to warn

---

charts/galoy/Chart.lock
charts/galoy/Chart.yaml

revert https://github.com/GaloyMoney/charts/pull/849

fix: revert pg changes from PR 849

---

charts/lnd/templates/statefulset.yaml

Increased rate at which LND is killed.

chore: kubemonkey to kill lnd every 2nd weekday (2.5x a week approx)

---

charts/lnd/Chart.yaml

update app version (it was not included in https://github.com/GaloyMoney/charts/pull/872)
FYI: previous update included it https://github.com/GaloyMoney/charts/pull/565/files

fix: update app version for lnd chart

---

charts/lnd/Chart.lock
charts/lnd/Chart.yaml
charts/lnd/templates/configmap.yaml
charts/lnd/templates/statefulset.yaml
charts/lnd/values.yaml
ci/testflight/lnd/main.tf
dev/bitcoin/lnd1.tf

This PR adds lnd on postgresql and makes it default.
Will break existing deployments without migration.

feat!: lnd on postgres

---

charts/bitcoind/templates/ingress.yaml
charts/galoy/charts/price/templates/ingress.yaml
charts/galoy/templates/admin-ingress.yaml
charts/galoy/templates/api-ingress.yaml
charts/lnd/charts/lndmon/templates/ingress.yaml
charts/specter/templates/ingress.yaml
dev/addons/dealer.tf
dev/addons/web-wallet-mobile-values.yml
dev/addons/web-wallet.tf
dev/bitcoin/lnd1.tf

as according to: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#ingress-v122
The Ingress API needs to change when running kubernetes v1.22.0 and above causing problem in the dev environment as discussed in: #1078
Staging is running kubernetes `1.21.12`
Inc is running `v1.21.11`
so the changes are compatible with them (networking.k8s.io/v1 API version, available since v1.19.)

feat!: ingress config for kubernetes >=v1.22

---

charts/bitcoind/templates/ingress.yaml
charts/galoy/charts/price/templates/ingress.yaml
charts/galoy/templates/admin-ingress.yaml
charts/galoy/templates/api-ingress.yaml
charts/lnd/charts/lndmon/templates/ingress.yaml
charts/specter/templates/ingress.yaml
dev/addons/dealer.tf
dev/addons/web-wallet-mobile-values.yml
dev/addons/web-wallet.tf
dev/bitcoin/lnd1.tf

Reverts GaloyMoney/charts#1101

feat!: revert ingress config for kubernetes >=v1.22

---

ci/testflight/galoy/testflight-values.yml
dev/galoy/galoy-values.yml

After adding https://github.com/GaloyMoney/galoy/pull/1389 this broke because the original code would merge in existing array elements from `default.yaml` while the new code replaces the array entirely.
These changes are to populate the new array that would otherwise be generated from original merge code and to include that entire array here.

fix: add required missing properties to test accounts yaml

---

charts/lnd/charts/loop/templates/statefulset.yaml

Reverts GaloyMoney/charts#1345

Revert "fix: remove lnd-storage mount for export-secrets"

---

charts/lnd/charts/loop/templates/statefulset.yaml

Reverts GaloyMoney/charts#1344

Revert "feat: fix loop chart export secrets"

---

charts/lnd/charts/loop/templates/export-secrets-configmap.yaml
charts/lnd/charts/loop/templates/statefulset.yaml

Reverts GaloyMoney/charts#1343

Revert "fix: loop chart yaml lint error"

---

charts/lnd/charts/loop/values.yaml

Reverts GaloyMoney/charts#1342

Revert "fix: sidecar image in loop chart"

---

charts/lnd/values.yaml

this will reduce attack surface when fees are high

chore: removing no-anchors: true

---

.github/workflows/dev-smoketest.yaml
charts/galoy-auth/templates/ingress.yaml
ci/tasks/bitcoind-smoketest.sh
ci/tasks/dealer-smoketest.sh
ci/tasks/dev-smoketest-settings.sh
dev/Makefile
dev/addons/admin-panel.tf
dev/addons/dealer.tf
dev/addons/galoy-pay.tf
dev/addons/main.tf
dev/addons/web-wallet.tf
dev/auth/auth-values.yml
dev/auth/main.tf
dev/bitcoin/lnd1.tf
dev/bitcoin/main.tf
dev/galoy/galoy-values.yml
dev/galoy/main.tf
dev/main.tf
dev/monitoring/main.tf
dev/smoketest/main.tf

Would provide proper feedback for so many pending PRs of dependency updates as well as new chart refactoring I'm planning to make.

ci: run smoketests as GitHub action against dev environment

---

charts/lnd/charts/loop/templates/export-secrets-configmap.yaml
charts/lnd/charts/loop/templates/statefulset.yaml

Reverts GaloyMoney/charts#1496

Revert "fix: export secret loop.fullname"

---

charts/monitoring/Chart.lock
charts/monitoring/Chart.yaml

Reverts GaloyMoney/charts#1423

revert: "chore(deps): update prometheus helm chart in monitoring"

---

ci/testflight/dealer/main.tf
dev/addons/dealer.tf

completing https://github.com/GaloyMoney/charts/pull/1539

fix: postgres creds for dealer on testflight, dev

---

charts/galoy-pay/Chart.yaml
charts/galoy-pay/values.yaml

Reverts GaloyMoney/charts#1435

Revert "chore-bump-galoy-pay-image-1bac1d3"

---

charts/stablesats/Chart.lock
charts/stablesats/Chart.yaml
charts/stablesats/templates/stablesats-cm.yaml
charts/stablesats/templates/stablesats-deployment.yaml
charts/stablesats/templates/stablesats-secrets.yaml
charts/stablesats/values.yaml
ci/pipeline.yml
ci/testflight/stablesats/main.tf
ci/testflight/stablesats/testflight-values.yml
ci/testflight/stablesats/testflight-values.yml.tmpl
ci/values.yml
dev/stablesats/main.tf
dev/stablesats/out
dev/stablesats/stablesats-values.yml
dev/stablesats/stablesats-values.yml.tmpl

Extend Stablesats chart to support user-trades and hedging modules.

feat:  stablesats hedging

---

ci/tasks/admin-panel-smoketest.sh
ci/tasks/dealer-smoketest.sh
ci/tasks/galoy-auth-smoketest.sh
ci/tasks/galoy-pay-smoketest.sh
ci/tasks/monitoring-smoketest.sh
ci/tasks/specter-smoketest.sh
ci/tasks/web-wallet-smoketest.sh

fix(smoketest): follow redirects

---

charts/lnd/values.yaml

all production and staging is running with bbolt so changing the dev env to bbolt too

chore: use bbolt by default for lnd 

---

charts/galoy/templates/admin-deployment.yaml
charts/galoy/templates/api-deployment.yaml
charts/galoy/templates/balance-notification-cronjob.yaml
charts/galoy/templates/exporter-deployment.yaml
charts/galoy/templates/galoy-cronjob.yaml
charts/galoy/templates/trigger-deployment.yaml
charts/galoy/values.yaml

Brings back tracing name prefix

chore: use tracing prefix for TRACING_SERVICE_NAME

---

charts/galoy/templates/NOTES.txt
charts/galoy/templates/galoy-secrets.yaml
charts/galoy/values.yaml

fix: postgres-price-history-creds didn't get provisioned

---

charts/stablesats/Chart.yaml
charts/stablesats/templates/stablesats-deployment.yaml

add `redinessProbe` and `livenessProbe` to stablesats.

chore: Stablesats health check

---

charts/lnd/charts/loop/templates/service.yaml
charts/lnd/charts/loop/templates/tests/test-connection.yaml
charts/lnd/charts/loop/values.yaml

This PR adds the loop grpc service ports

feat: loop grpc service port

---

charts/stablesats/Chart.yaml
charts/stablesats/values.yaml

Reverts GaloyMoney/charts#1722

revert "chore(deps) bump-stablesats-image-2930370"

---

charts/galoy/templates/api-ingress.yaml

Reverts GaloyMoney/charts#1730

Revert "fix: nginx websocket connections"

---

charts/galoy/templates/api-ingress.yaml

Temporarily increase rate limit until internal networking is fix.

chore: Increase rate limit

---

charts/galoy/templates/api-ingress.yaml

Reverts GaloyMoney/charts#1774

Revert "chore: Increase rate limit"

---

charts/lnd/Chart.yaml
charts/lnd/values.yaml
images/lnd-sidecar/Dockerfile

hot fix for the LND wire parsing bug https://github.com/lightningnetwork/lnd/pull/7004

chore: update lnd docker images to v0.15.2-beta

---

dev/galoy/main.tf

Since Oauthkeeper was added, the endpoint got changed that was not changed in Dev.

ci: fix github action smoketest for galoy

---

charts/galoy/templates/api-deployment.yaml
charts/galoy/templates/galoy-secrets.yaml
charts/galoy/values.yaml
ci/pipeline.yml
ci/testflight/galoy/main.tf
ci/values.yml
dev/galoy/main.tf

related to https://github.com/GaloyMoney/galoy/pull/1811

chore: removing apollo analytics (has been superseeded by opentelemetry)

---

.github/workflows/dev-smoketest.yaml
dev/Makefile

Tested ingress locally, let's see if smoke-tests pass.

chore: upgrade to Kubernetes v1.23

---

charts/galoy/Chart.lock
charts/galoy/Chart.yaml
charts/galoy/values.yaml
ci/tasks/galoy-smoketest.sh
ci/testflight/galoy/main.tf
dev/galoy/main.tf

Add Kratos to galoy lifecycle:

chore: bring kratos to galoy chart

---

ci/testflight/galoy-deps/main.tf
dev/galoy-deps/main.tf

A new provider is being added to get around the CRD issue with terraform. Read more [here](https://github.com/hashicorp/terraform-provider-kubernetes/issues/1367).

chore: add topic creation to deps testflight

---

ci/testflight/galoy-deps/main.tf

Reverts GaloyMoney/charts#1934

Revert "chore: add smoketest kubeconfig to deps smoketest secret"

---

ci/testflight/galoy-deps/main.tf

Reverts GaloyMoney/charts#1935

Revert "Revert "chore: add smoketest kubeconfig to deps smoketest secret""

---

charts/galoy-pay/Chart.yaml
charts/galoy-pay/values.yaml

Reverts GaloyMoney/charts#1987

Revert "chore-bump-galoy-pay-image-a43c195"

---

charts/galoy-deps/values.yaml

This has already been tested and works correctly

fix: otel values env var syntax

---

charts/galoy-deps/values.yaml

This has already been tested and works correctly

fix: otel prom config env var syntax

---

ci/testflight/galoy-deps/testflight-values.yml

Reverts GaloyMoney/charts#2160

Revert "ci: disable rbac in kubemonkey testflight"

---

charts/galoy/Chart.lock
charts/galoy/Chart.yaml

Related to https://github.com/GaloyMoney/galoy/pull/2047

chore: downgrade mongodb chart in galoy

---

ci/testflight/galoy/testflight-values.yml

~~Fix the loop secret names after changed in https://github.com/GaloyMoney/charts/pull/2163~~

fix: disable loop for testflight on signet

---

charts/galoy-auth/Chart.lock
charts/galoy-auth/Chart.yaml
charts/galoy/Chart.lock
charts/galoy/Chart.yaml

- and underlying version? aiming to get kratos v0.11 in prod

chore: updating kratos and oathkeeper charts

---

charts/stablesats/Chart.lock
charts/stablesats/Chart.yaml

Reverts GaloyMoney/charts#2360

revert: "chore(deps): update postgresql helm chart in stablesats"

---

charts/galoy/templates/api-deployment.yaml
charts/galoy/templates/balance-notification-cronjob.yaml
charts/galoy/templates/exporter-deployment.yaml
charts/galoy/templates/galoy-cronjob.yaml
charts/galoy/templates/trigger-deployment.yaml
charts/loop/charts/loopserver/templates/statefulset.yaml
charts/loop/templates/statefulset.yaml
charts/rtl/templates/deployment.yaml
dev/smoketest/main.tf

- chore: remove leftover lnd network policy label
- ci: cleanup smoketest pod labels

chore: cleanup labels

---

charts/stablesats/Chart.lock
charts/stablesats/Chart.yaml
charts/stablesats/templates/stablesats-dealer-cm.yaml
charts/stablesats/templates/stablesats-dealer-deployment.yaml
charts/stablesats/templates/stablesats-price-cm.yaml
charts/stablesats/templates/stablesats-price-deployment.yaml
charts/stablesats/templates/stablesats-price-svc.yaml
charts/stablesats/templates/stablesats-secrets.yaml
charts/stablesats/values.yaml
ci/testflight/galoy-auth/galoy-auth-testflight-values.yml.tmpl
ci/testflight/galoy-auth/main.tf
ci/testflight/galoy-auth/postgres-testflight-values.yml.tmpl
dev/stablesats/main.tf
dev/stablesats/stablesats-values.yml.tmpl

Separating stablesats into a price and dealer deployment to help with resilience.

feat!: seperate stablesats price

---

ci/tasks/galoy-smoketest.sh
ci/testflight/galoy/main.tf
dev/galoy/main.tf

Reverts GaloyMoney/charts#2476

revert: chore: add oathkeeper_api and kratos_public smoketests

---

charts/galoy/templates/api-ingress.yaml
charts/galoy/values.yaml
dev/Makefile
dev/README.md
dev/galoy/galoy-regtest-values.yml
dev/galoy/kratos-values.yml.tmpl
dev/galoy/main.tf

Related to #2515
Separated the Kratos related settings from the reverted PR: https://github.com/GaloyMoney/charts/pull/2474
The Oathkeeper related changes are in: https://github.com/GaloyMoney/charts/pull/2515

chore: set kratos defaults and dev env

---

charts/galoy/values.yaml
dev/galoy/galoy-regtest-values.yml
dev/galoy/galoy-signet-values.yml

related to: https://github.com/GaloyMoney/galoy/pull/2254

chore: add defaults for galoy kratos values

---

ci/tasks/galoy-smoketest.sh
ci/testflight/galoy/main.tf
ci/testflight/galoy/testflight-values.yml
ci/testflight/galoy/testflight-values.yml.tmpl
dev/galoy/galoy-regtest-values.yml
dev/galoy/galoy-signet-values.yml
dev/galoy/galoy-values.yml.tmpl
dev/galoy/main.tf

Leaving as a placeholder for @krtk6160 and @openoms on how to fix the authenticated smoketests and admin api endpoint issue in staging.

feat: authenticated smoketests

---

ci/tasks/galoy-smoketest.sh
ci/testflight/galoy/kratos-values.yml.tmpl
ci/testflight/galoy/main.tf
ci/testflight/galoy/testflight-values.yml
dev/galoy/galoy-regtest-values.yml
dev/galoy/galoy-signet-values.yml
dev/galoy/kratos-values.yml.tmpl
dev/galoy/main.tf

Reverts GaloyMoney/charts#2615

revert: feat: authenticated smoketests

---

charts/galoy/values.yaml
dev/galoy/galoy-regtest-values.yml

This will make the admin ingress work OOTB

chore: move admin ingress config to default values

---

charts/galoy/values.yaml
dev/galoy/galoy-regtest-values.yml

Reverts GaloyMoney/charts#2679

Revert "chore: move admin ingress config to default values"

---

ci/tasks/galoy-smoketest.sh
ci/testflight/galoy/main.tf
ci/testflight/galoy/postgresql-values.yml
ci/testflight/galoy/testflight-values.yml
ci/testflight/galoy/testflight-values.yml.tmpl
dev/galoy/galoy-regtest-values.yml
dev/galoy/galoy-signet-values.yml
dev/galoy/galoy-values.yml.tmpl
dev/galoy/main.tf

Adding a postgresql instance for kratos the same as it done for the dev env in https://github.com/GaloyMoney/charts/pull/2426/files to make authentication work in testflight.
Changing to use a templatefile on both dev and testflight for the test accounts.

Authenticated smoketests2

---

charts/galoy/Chart.yaml
charts/galoy/values.yaml

Reverts GaloyMoney/charts#2739
Rollout caused issues https://ci.galoy.io/teams/galoy/pipelines/galoy-deployments/jobs/galoy-bbw-galoy/builds/426 reverting to unblock pipeline.

revert: "chore(deps): bump-galoy-image-23c8e2a"

---

charts/galoy/Chart.yaml
charts/galoy/values.yaml

Reverts GaloyMoney/charts#2732

revert: "chore(deps): bump-galoy-image-bd487c2"

---

charts/galoy-deps/templates/kafka-cluster.yaml
charts/galoy-deps/values.yaml
dev/Makefile
dev/galoy-deps/kafka-values.yml.tmpl

Adds the Kafka Connect cluster to the dev setup with a functional mongo-source-connector pulling only from the medici databases.

chore: prepare for kafka connect

---

charts/galoy/charts/price/values.yaml

Reverts GaloyMoney/charts#2807

revert: "chore(deps): bump-price-image-edcb474"

---

.github/workflows/dev-smoketest.yaml
charts/bria/.helmignore
charts/bria/Chart.lock
charts/bria/Chart.yaml
charts/bria/templates/_helpers.tpl
charts/bria/templates/bria-admin-svc.yaml
charts/bria/templates/bria-api-svc.yaml
charts/bria/templates/bria-cm.yaml
charts/bria/templates/bria-deployment.yaml
charts/bria/templates/bria-sa.yaml
charts/bria/templates/bria-secrets.yaml
charts/bria/values.yaml
ci/pipeline-fragments.lib.yml
ci/tasks/bria-smoketest.sh
dev/bitcoin/bria-values.yml
dev/bitcoin/bria.tf

Get https://github.com/GaloyMoney/bria into production.

feat: bria chart

---

ci/pipeline-fragments.lib.yml

ci: add fulcrum to bitcoin

---

charts/fulcrum/templates/_helpers.tpl
charts/fulcrum/templates/serviceaccount.yaml
charts/fulcrum/templates/statefulset.yaml

This will bring the fulcrum chart more in line with our best practices inspired from the concourse chart

refactor: remove svc account boilerplate fulcrum chart

---

charts/lnd/templates/export-secrets-configmap.yaml

feat: add lnd xpub to secrets

---

charts/galoy/charts/price/templates/history-deployment.yaml
charts/galoy/charts/price/templates/realtime-deployment.yaml
charts/galoy/charts/price/values.yaml

This should fix realtime price pod not being scraped by prometheus.

fix: price pod annotations scope

---

charts/galoy-deps/values.yaml

See [otel chart changelog](https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md#0531-to-0540) for more details.
Related to https://github.com/GaloyMoney/charts/pull/2923

chore: add otel resource limits

---

charts/galoy/Chart.lock
charts/galoy/Chart.yaml

Reverts GaloyMoney/charts#2934

revert: "chore(deps): update kratos helm chart in galoy"

---

charts/lnd/Chart.yaml
charts/lnd/values.yaml
images/lnd-sidecar/Dockerfile

to match the version in galoy https://github.com/GaloyMoney/galoy/pull/2506

chore: update lnd images to v0.16.1

---

charts/bitcoind/values.yaml

Reverts #2967 in attempt to reduce mem usage

chore: reduce bitcoind rpc work queue

---

images/lnd-sidecar/Dockerfile

Update sidecar.. was not updated here https://github.com/GaloyMoney/charts/pull/2995

fix: update sidecar lnd version to v0.16.2-beta

---

dev/signet.md

Completes #1123 with documentation.

docs: testing on signet

---

ci/testflight/admin-panel/main.tf
ci/testflight/bitcoind/main.tf
ci/testflight/bria/main.tf
ci/testflight/dealer/main.tf
ci/testflight/fulcrum/main.tf
ci/testflight/galoy-auth/main.tf
ci/testflight/galoy-pay/main.tf
ci/testflight/galoy/main.tf
ci/testflight/lnd/main.tf
ci/testflight/monitoring/main.tf
ci/testflight/rtl/main.tf
ci/testflight/specter/main.tf
ci/testflight/stablesats/main.tf
ci/testflight/web-wallet/main.tf

- ci(testflight): pin gcp provider to last working version

ci: pin gcp provider version

---

.github/workflows/dev-smoketest.yaml
dev/bitcoin/bria.tf

Fixes the dev setup and github actions. Includes #3110

fix: add signer-encryption-key to dev

---

charts/admin-panel/templates/deployment.yaml
charts/admin-panel/values.yaml
charts/bria/templates/bria-deployment.yaml
charts/bria/values.yaml
charts/dealer/templates/dealer-deployment.yaml
charts/dealer/values.yaml
charts/galoy-deps/values.yaml
charts/galoy-pay/templates/deployment.yaml
charts/galoy-pay/values.yaml
charts/galoy/charts/price/templates/history-cronjob.yaml
charts/galoy/charts/price/templates/history-migration-job.yaml
charts/galoy/charts/price/values.yaml
charts/galoy/templates/api-deployment.yaml
charts/galoy/templates/balance-notification-cronjob.yaml
charts/galoy/templates/exporter-deployment.yaml
charts/galoy/templates/galoy-cronjob.yaml
charts/galoy/templates/galoy-migration-job.yaml
charts/galoy/templates/mongo-backup-cronjob.yaml
charts/galoy/templates/trigger-deployment.yaml
charts/galoy/values.yaml
charts/lnd/values.yaml
charts/loop/values.yaml
charts/mempool/templates/statefulset.yaml
charts/monitoring/values.yaml
charts/stablesats/templates/stablesats-dealer-deployment.yaml
charts/stablesats/templates/stablesats-price-deployment.yaml
charts/stablesats/values.yaml
charts/web-wallet/templates/deployment.yaml
charts/web-wallet/values.yaml

- chore: expose admin panel resource config
- chore: expose bria resource config
- chore: expose dealer resource config
- chore: expose deps resource config
- chore: expose galoy pay resource config
- chore: expose galoy pods resource config
- chore: expose lnd resource config
- chore: expose loop resource config
- chore: expose mempool resource config
- chore: expose monitoring resource config
- chore: expose stablesats resource config
- chore: expose web wallet resource config

chore: expose resource config in charts

---

charts/bitcoind/values.yaml

context keybase://chat/galoymoney#dev/9149

chore: enable shrinkdebugfile by default

---

ci/pipeline-fragments.lib.yml
ci/pipeline.yml
images/kafka-connect/Dockerfile

the local build of the docker image is working

feat: add kafka connect image

---

charts/galoy/templates/_helpers.tpl
charts/galoy/templates/websocket-deployment.yaml
charts/galoy/templates/websocket-ingress.yaml
charts/galoy/templates/websocket-service.yaml
charts/galoy/values.yaml

feat: dedicated websocket pod

---

charts/galoy/templates/api-deployment.yaml
charts/galoy/templates/balance-notification-cronjob.yaml
charts/galoy/templates/exporter-deployment.yaml
charts/galoy/templates/galoy-cronjob.yaml
charts/galoy/templates/trigger-deployment.yaml
charts/galoy/values.yaml

to be merged after https://github.com/GaloyMoney/galoy/pull/2812

chore!: upgrade to otlp from jaeger

---

images/kafka-connect/Dockerfile

Adding deps to the mongo source connector to be able to use  the FileConfigProvider https://docs.confluent.io/platform/current/connect/security.html#fileconfigprovider

build: add deps and updates to kafka-connect image

---

charts/galoy-deps/values.yaml
charts/galoy/values.yaml

charts config for https://github.com/GaloyMoney/galoy/pull/2713

feat: email login config

---

charts/galoy-pay/templates/deployment.yaml
charts/galoy-pay/values.yaml
ci/testflight/galoy-pay/main.tf
ci/testflight/galoy-pay/testflight-values.yml.tmpl

to be merged with this charts config https://github.com/GaloyMoney/galoy-pay/pull/521

feat: galoy pay config for dedicated websocket server

---

charts/galoy/values.yaml

to be merged with https://github.com/GaloyMoney/galoy/pull/2943

feat: email cookie login config

---

charts/galoy/values.yaml

default has been remove in main but commit not present in latest release
https://github.com/ory/kratos/pull/3464/files

chore: still need earlier extend

---

images/kafka-connect/Dockerfile

Adding a minor update of the postgres source connector to trigger the kafka-connect pipeline.

chore: update kafka debezium-connector-postgres

---

charts/lnd/values.yaml
images/lnd-sidecar/Dockerfile

release notes https://github.com/lightningnetwork/lnd/blob/v0.17.3-beta/docs/release-notes/release-notes-0.17.3.md

chore: update lnd version to v0.17.3-beta

---

charts/fulcrum/Chart.yaml
charts/fulcrum/values.yaml

https://github.com/cculianu/Fulcrum/releases/tag/v1.9.7
>Fixed a rare corner-case race condition leading to a potential "abort" out of Fulcrum (server death), in very rare cases while synching mempool. It wouldn't lead to data corruption but could be highly annoying. Probability of it occurring was close-to-but-not-0.

chore: fulcrum update to v1.9.7

---

ci/tasks/galoy-pay-smoketest.sh

pending task from last galoy pay incident

ci(pay): update smoketest to include invoice request validation

---

dev/galoy/galoy-regtest-values.yml
dev/galoy/galoy-signet-values.yml

See https://github.com/GaloyMoney/galoy/pull/3916

chore: remove swap-related configs

---

charts/galoy/Chart.yaml
charts/galoy/apollo-router/supergraph.graphql
charts/galoy/values.yaml

Reverts GaloyMoney/charts#5645
Reverting due to issue with scopes migration

revert: "chore(deps): bump-core-bundle-images-a19f31f"

---

charts/galoy/values.yaml

Reverts GaloyMoney/charts#5640

revert: "chore(deps): bump-api-keys-image-a19f31f"

---

charts/galoy/values.yaml

Reverts GaloyMoney/charts#5643

revert: "chore(deps): bump-notifications-image-a19f31f"

---

charts/lnd/values.yaml
images/lnd-sidecar/Dockerfile

To be merged after https://github.com/GaloyMoney/galoy/pull/4060

chore: update lnd to v0.17.4-beta

---

charts/admin-panel/templates/deployment.yaml
charts/admin-panel/templates/secrets.yaml
charts/admin-panel/values.yaml
ci/testflight/admin-panel/main.tf
dev/addons/Tiltfile

To be merged after https://github.com/GaloyMoney/charts/pull/5691

chore: remove github oauth from admin panel

---

charts/galoy-pay/templates/deployment.yaml
charts/galoy-pay/templates/secrets.yaml
charts/galoy-pay/values.yaml
ci/testflight/galoy-pay/main.tf
ci/testflight/galoy-pay/testflight-values.yml
dev/addons/Tiltfile
dev/addons/galoy-pay-values.yml

merge after this : https://github.com/GaloyMoney/galoy/pull/4149

chore(pay): adding next-auth variables

---

charts/galoy-pay/values.yaml

chore(pay): added dummy values

---

charts/galoy/charts/price/templates/realtime-deployment.yaml
charts/galoy/charts/price/values.yaml

Merge after https://github.com/GaloyMoney/price/pull/64

chore(price-realtime): add enableFilter setting

---

charts/galoy/templates/api-deployment.yaml
charts/galoy/values.yaml

Follows from: https://github.com/GaloyMoney/galoy/pull/4226

chore: add 'OTEL_TRACES_SAMPLER' to api pod

---

charts/cala/templates/cala-cm.yaml
charts/cala/values.yaml

should be merged after new release of cala

chore: remove serverId

---

charts/cala/templates/cala-deployment.yaml
charts/cala/values.yaml

For injecting extra environment variables into the runtime of cala

chore: extra env secrets for cala

---

charts/lnd/values.yaml
images/lnd-sidecar/Dockerfile

Merge after https://github.com/GaloyMoney/blink/pull/4509
Release notes: https://github.com/lightningnetwork/lnd/blob/master/docs/release-notes/release-notes-0.18.0.md

chore: update lnd to v0.18.0-beta

---

.github/workflows/cleanup-after-pr-closed.yaml

cosmetic name change
tested ok when closed

build: add name cleanup-after-pr-closed

---

charts/stablesats/Chart.lock
charts/stablesats/Chart.yaml

This PR updates Posgres Helm Chart Dependencies PG11 -> PG14.

chore(deps): update postgresql helm chart in stablesats

---

ci/testflight/galoy/testflight-values.yml

match the new setting in the staging environment

ci!: change testflight backup bucketName

---

charts/lnd/values.yaml
images/lnd-sidecar/Dockerfile

Merge after all tests pass https://github.com/GaloyMoney/blink/pull/4691

chore: update lnd version to v0.18.4-beta

---

charts/galoy/charts/price/templates/history-deployment.yaml
charts/galoy/charts/price/values.yaml

Merge after https://github.com/GaloyMoney/price/pull/70
replicate realtime filter setting https://github.com/GaloyMoney/charts/pull/5955

chore(price-history): add enableFilter setting

---

charts/stablesats/Chart.lock
charts/stablesats/Chart.yaml

Reverts GaloyMoney/charts#7530
Broke testflight

revert: chore(deps): update postgresql helm chart in stablesats

---

charts/galoy/templates/_helpers.tpl
charts/galoy/templates/galoy-secrets.yaml
charts/galoy/values.yaml
ci/testflight/galoy/main.tf
dev/galoy/Tiltfile

required for https://github.com/GaloyMoney/blink/pull/4798

feat: add twilio messaging env variables

---

ci/tasks/galoy-smoketest.sh

only a comment change, but can be used to trigger the pipeline

chore: change reference to price repo

---

ci/testflight/bitcoind/main.tf
ci/testflight/bria/main.tf
ci/testflight/fulcrum/main.tf
ci/testflight/galoy-deps/main.tf
ci/testflight/kafka-connect/main.tf
ci/testflight/lnd/main.tf
ci/testflight/map/main.tf
ci/testflight/mempool/main.tf
ci/testflight/monitoring/main.tf
ci/testflight/specter/main.tf
ci/testflight/stablesats/main.tf
ci/testflight/voucher/main.tf

following up the fix in https://github.com/blinkbitcoin/charts/pull/7899
and same done in deployments

fix: pin helm provider to 2.0 in all testflights

---

charts/fulcrum/Chart.yaml
charts/fulcrum/values.yaml

Nore regarding the version on Docker Hub: https://github.com/cculianu/Fulcrum/issues/281

chore: fulcrum update to v1.12.0

---

charts/galoy/Chart.yaml
charts/galoy/values.yaml

Reverts blinkbitcoin/charts#7934

Revert "chore(deps): bump-core-bundle-images-ce90d9f"

---

charts/galoy/values.yaml

Update config according to https://github.com/blinkbitcoin/blink/pull/92

chore: update galoy bria config

---

charts/galoy-deps/values.yaml

it will reduce around 1M per day
https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/dBZnjZw5Be5?vs=hideCompare

chore: update ottl router filters

---

charts/galoy-deps/values.yaml

Reverts blinkbitcoin/charts#8200

revert: "chore: update ottl router filters"

---

charts/admin-panel/templates/deployment.yaml
dev/addons/admin-panel-values.yml

Should fix this job run:
https://ci.blink.sv/teams/dev/pipelines/helm-charts/jobs/admin-panel-testflight/builds/167
```
Plan: 4 to add, 0 to change, 0 to destroy.
kubernetes_namespace.testflight: Creating...
kubernetes_secret.admin_panel: Creating...
kubernetes_secret.smoketest: Creating...
kubernetes_namespace.testflight: Creation complete after 1s [id=admin-panel-testflight-6133e42]
helm_release.admin_panel: Creating...
kubernetes_secret.smoketest: Creation complete after 1s [id=galoy-staging-smoketest/admin-panel-testflight-6133e42]
kubernetes_secret.admin_panel: Creation complete after 1s [id=admin-panel-testflight-6133e42/admin-panel]
╷
│ Warning: Helm release "" was created but has a failed status. Use the `helm` command to investigate the error, correct it, then run Terraform …
```

fix: Json rendering issue on admin-panel

---

charts/voucher/values.yaml

Reverts blinkbitcoin/charts#8265

revert: "chore(deps): bump-voucher-image-4b3930c"
