- charts/bitcoind/Chart.yaml
- charts/bitcoind/templates/_helpers.tpl
- charts/bitcoind/templates/configmap.yaml
- charts/bitcoind/templates/secrets.yaml
- charts/bitcoind/templates/statefulset.yaml
- charts/bitcoind/values.yaml
- ci/image/Dockerfile
- ci/pipeline.yml
- ci/repipe
- ci/tasks/bitcoind-smoketest.sh
- ci/tasks/prepare-testflight.sh
- ci/testflight/bitcoind/main.tf
- ci/testflight/bitcoind/testflight-values.yml
- ci/values.yml
This enables determining the rpcpassword either via values.yml or via pre-provisioning a secret.
Password generation as part of the helm chart is not standard practice.
Potentially breaking change. Must specify:
```
secrets:
create: false
```
In existing installations to not override the secret.
Build on https://github.com/GaloyMoney/charts/pull/49
Addresses https://github.com/GaloyMoney/charts/issues/44
> No rpcpassword generation

- charts/bitcoind/templates/configmap.yaml
- charts/bitcoind/templates/secrets.yaml
- charts/bitcoind/templates/statefulset.yaml
- charts/bitcoind/values.yaml
- ci/image/Dockerfile
- ci/pipeline.yml
- ci/repipe
- ci/tasks/bitcoind-smoketest.sh
- ci/tasks/prepare-testflight.sh
- ci/testflight/bitcoind/main.tf
- ci/testflight/bitcoind/testflight-values.yml
- ci/values.yml
There is no point of using a `secret` for the confidential `rpcpassword` if it is exposed as part of the `configmap`. This PR provisions the `rpcpassword` to the pod via a secret mount.
Built off of https://github.com/GaloyMoney/charts/pull/48
Part of https://github.com/GaloyMoney/charts/issues/44
> Password out of configmap

- dev/Makefile
Fixed the k3s server args in the create-cluster command, cluster not waking up issue fixed.
Related Issue: https://github.com/rancher/k3d/issues/742
> [k3d] create cluster args fixed

- charts/galoy/Chart.lock
- charts/galoy/Chart.yaml
PR that goes with: https://github.com/GaloyMoney/galoy/pull/706
> update mongodb to last v4 version

- ci/testflight/dealer/testflight-values.yml
Empties out the testflight values file for dealer to reproduce same persistence issue on testflight.
Almost reverts https://github.com/GaloyMoney/charts/pull/229/files
> Reenabled persistence from dealer on testflight

- charts/galoy/charts/price/values.yaml
This is so that yq can pick it up.
The updated logic for PRs via price pipeline is present in this associated PR: https://github.com/GaloyMoney/price/pull/11
> Removing commented git_ref from price

- charts/dealer/values.yaml
- ci/pipeline.yml
- ci/testflight/dealer/testflight-values.yml
- ci/values.yml
- dev/addons/dealer-values.yml
- dev/addons/dealer.tf
Also accommodates `pg-shared-admin-password` for staging ci pipeline.
> Postgres chart disabled by default for dealer - enabled it for testflight and dev

- ci/pipeline-fragments.lib.yml
- ci/pipeline.yml
This allows context based current head searching.
Hardcodes `branch: main` to repo resource name so not to share cache with it's `out` counterpart.
> Fix dealer staging pipeline

- ci/pipeline-fragments.lib.yml
- ci/tasks/bump-dashboard.sh
- ci/tasks/bump-dealer-dashboard.sh
Adds CI Pipeline `if` blocks for dealer in order to sync grafana dashboard accross.
https://github.com/GaloyMoney/galoy-deployments/pull/617 should be in before this merges.
> Added pipeline steps for dealer's grafana vendir sync

- charts/monitoring/values.yaml
Looks like the metrics are being scraped twice. `kubernetes-pods` task was dropped for lnd pods as well. Doing the same for dealer.
> Drops dealer scraping twice

- ci/pipeline-fragments.lib.yml
This converts Concourse Resource names to `env-depl` because `gcp-galoy-staging-addons` make more sense than `addons-gcp-galoy-staging`.
> Flip depl-env to env-depl naming

- charts/galoy/templates/deployment.yaml
- charts/galoy/values.yaml
- ci/testflight/galoy/main.tf
- dev/galoy/main.tf
Reverts GaloyMoney/charts#399
Required to unblock `galoy-staging-galoy` pipeline, needs secret adition and when it's complete, will recreate this.
> Revert "chore: modify galoy chart to use twilio auth token"

- charts/galoy/templates/deployment.yaml
- charts/galoy/values.yaml
- ci/testflight/galoy/main.tf
- dev/galoy/main.tf
Redeploys https://github.com/GaloyMoney/charts/pull/399, coz it was reverted - now, should work at staging.
> chore: modify galoy chart to use twilio auth token

- charts/lnd/templates/statefulset.yaml
> fix: Use exec for tor container

- charts/galoy/templates/deployment.yaml
- charts/galoy/templates/migration-job.yaml
- charts/galoy/values.yaml
This PR adds a job that executes all database migrations and an init_container to the deployments of the galoy chart.
The init_container ensures that the new app code doesn't start until the migration has completed.
> feat: automatically migrate db pre-stratup

- ci/pipeline-fragments.lib.yml
Updated on CI already.
To prevent cases like https://github.com/GaloyMoney/galoy-deployments/pull/992#issuecomment-1019309001
> ci: ignore path Chart.yaml

- charts/galoy/templates/cronjob.yaml
- charts/galoy/templates/deployment.yaml
- charts/galoy/templates/migration-job.yaml
I found out that the fix isn't necessary and what we want is supported by adding the `-wr` postfix to the argument (see https://github.com/groundnuty/k8s-wait-for/blob/master/wait_for.sh#L234)
> fix: no need for bodymindarts fork of k8s-wait-for

- ci/pipeline-fragments.lib.yml
Updated CI.
Tested in a seperate pipeline, works as expected.
> ci: ignore path Chart.yaml properly

- charts/lnd/values.yaml
Allow lnd to connect to non-onion services directly via clearnet (improve performance of probing and payments)
https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf#L840
> feat: add skip-proxy-for-clearnet-targets to lnd

- charts/galoy/templates/mongo-backup-configmap.yaml
Attempt to fix the error message on backup upload:
```
curl: (92) HTTP/2 stream 1 was not closed cleanly before end of the underlying stream
```
see https://stackoverflow.com/questions/56413290/getting-curl-92-http-2-stream-1-was-not-closed-cleanly-internal-error-err
> fix: force http1.1 for dropbox upload

- charts/lnd/values.yaml
this would be better than `largest` as this would limit the risk of too many unconfirmed transactions in the mempool
> chore: make coin selection random

- charts/lnd/values.yaml
this is increasing potential discrepency between the onchainFee calculation for fee check, and real fees being paid, because the UXTOs used would be different with a random selection. Without the random selection, the fees would likely be the same between the "feeProbe" and "realFee"
> fix: remove random coin selection

- charts/web-wallet/templates/deployment.yaml
- charts/web-wallet/values.yaml
- ci/testflight/web-wallet/web-wallet-mobile-testflight-values.yml
- dev/addons/web-wallet-mobile-values.yml
Let us start having a top level `<application>:` key to group the app specific settings instead of putting so many settings loosely on top level.
> refactor: introduce top level webWallet key

- charts/galoy/Chart.lock
- charts/galoy/Chart.yaml
- dev/galoy/galoy-values.yml
It looks like the right way to render nested dependencies is to declare them in the top level chart's dependencies. Without this,  helm will silently ignore the nested dependency, which is what we were experiencing on the price chart's testflight.
We can still conditionally render it by using the correct scoping in the `condition` block.
> fix: add postgres as dependency to galoy chart

- charts/galoy/values.yaml
This will fix the failing mongo backup job which is indirectly blocking all backend pods
> chore: bump mongo tools to 4.2.14

- images/lnd-sidecar/Dockerfile
The sidecar image needs to be updated now that we are using LND `0.14.3-beta`
> chore(deps): bump lnd in sidecar image

- ci/pipeline.yml
- ci/tasks/bump-image-digest.sh
- ci/tasks/open-image-bump-pr.sh
This PR will genericize the image building tasks, allowing them to be reused for other builds like the mongo backup image
> ci: genericize image build and bump tasks

- charts/lnd/templates/configmap.yaml
- ci/testflight/lnd/testflight-values.yml
Removes network pinning on customValues requirement in lnd config. Sets from `global.network`.
> refactor: remove network from lnd customValues

- charts/bitcoind/templates/ingress.yaml
- charts/galoy/charts/price/templates/ingress.yaml
- charts/galoy/templates/admin-ingress.yaml
- charts/galoy/templates/api-ingress.yaml
- charts/lnd/charts/lndmon/templates/ingress.yaml
- charts/specter/templates/ingress.yaml
- dev/addons/dealer.tf
- dev/addons/web-wallet-mobile-values.yml
- dev/addons/web-wallet.tf
- dev/bitcoin/lnd1.tf
Proposing again as it was merged before:  #1101, but was reverted in #1114  because the galoy-smoketest on staging failed after the last merge which can be related to the testnet blockstorm at the time as well.
The changes are compatible with kubernetes > 1.19, but needed to run the new installs using >1.22
There are some small fixes also affecting only the dev environment.
Tests were successful locally.
> feat!: reintroduce ingress config for kubernetes >=v1.22 

- charts/galoy/templates/mongo-backup-configmap.yaml
This PR will change the destination of the mongodb backups from the root of the gcs bucket to a pseudo directory inside it.
> chore: move mongodb backups to subpath

- charts/lnd/charts/loop/values.yaml
overrides #1197 using the correct image for the loop client
> chore: update loop to v0.19.1-beta

- charts/rtl/templates/configmap_and_secret.yaml
- charts/rtl/templates/deployment.yaml
- charts/rtl/values.yaml
This PR changes the configuration map to iterate over an array of lnd values. I have also added the possibility to enable dark mode and themes.
I've also set the channelBackupPath to a place where the rtl process has write access - else you get error messages with each channel open or close.
**!This changes the values structure!**
Here is an example for two lnds in the new format:
```
lnds:
- url: lnd1
secretName: lnd1-credentials
dark: true
themeColor: YELLOW
- url: lnd2
secretName: lnd2-credentials
dark: false
themeColor: BLUE
```
The possible values for themeColor are:  BLUE GREEN INDIGO PINK PURPLE TEAL YELLOW
UPDATE: Updated to match new naming convention.
> feat: array input for lnd values in ride the lightning config

- ci/testflight/dealer/testflight-values.yml
The postgresql chart was refactored and thus the key for persistence was moved under a new `primary` key. This PR should bring our testflight-values.yml in line with what the latest chart expects.
> fix: disable pg persistence on dealer testflight

- charts/galoy/templates/deployment.yaml
- charts/lnd/charts/loop/templates/export-secrets-configmap.yaml
- charts/lnd/charts/loop/templates/service.yaml
- charts/lnd/charts/loop/templates/statefulset.yaml
- charts/lnd/charts/loop/values.yaml
- images/lnd-sidecar/Dockerfile
This PR adds config for loopout automation. See https://github.com/GaloyMoney/galoy/pull/1396 
The loop service has its own `loop.macaroon` and tls cert that the `main galoy backend` needs to talk to the loop grpc endpoint. This PR adds the secrets and config.
> feat: add loopout automation config to the loop chart

- charts/lnd/values.yaml
Having the sync-freelist=1 :
>will decrease
start up time, but can result in performance degradation for very large
databases, and also result in higher memory usage.
https://github.com/lightningnetwork/lnd/blob/fec8fd9c63dc672dc3ea1b9be47bd1d6c4a0a54d/sample-lnd.conf#L89
>you'll see very high CPU usage with large database, since it needs to sort+write the freelist to disk each time. The default setting trades that off for longer start times, since the freelist needs to be reconstructed at start up each time.
https://github.com/lightningnetwork/lnd/issues/6737#issuecomment-1195726285
This PR will switch it off everywhere as it is not specified for the individual deployments.
> chore: remove sync-freelist setting to use default

- ci/testflight/galoy/main.tf
- ci/testflight/galoy/testflight-values.yml
Test improved security of running redis with injected password (instead of default).
> fix: run galoy-testflight with injected redis password

- charts/galoy-auth/templates/_helpers.tpl
- charts/galoy-auth/templates/ingress.yaml
- charts/stablesats/.helmignore
- charts/stablesats/Chart.lock
- charts/stablesats/Chart.yaml
- charts/stablesats/templates/_helpers.tpl
- charts/stablesats/templates/stablesats-cm.yaml
- charts/stablesats/templates/stablesats-deployment.yaml
- charts/stablesats/templates/stablesats-price-svc.yaml
- charts/stablesats/values.yaml
- dev/stablesats/main.tf
- dev/stablesats/out
- dev/stablesats/stablesats-values.yml
This is an initial version of the Stablesats chart.
It works locally (though hasn't been integrated into `dev/main.tf` to bring it up go to `dev/stablesats` and run `tf apply`) and I would like to start building the smoktest via iteration on concourse.
> feat: initial stablesats chart (price-server)

- charts/galoy/templates/deployment.yaml
for migrating from the auto created redis secret to a pre-generated one
we must use a different name
> fix: redis auth

- ci/tasks/galoy-smoketest.sh
note: this is not ideal that we may have to wait 1m + for the reconnect
to timeout and go to the next step
plus it seems the timeout is 1m/node?
https://github.com/alexbosworth/balanceofsatoshis/blob/master/network/reconnect.js
it really feels like reconnect should be run in parallel with the other commands
> chore: extend timeout to accomodate new reconnect function

- .github/workflows/dev-smoketest.yaml
Manually verified that removing concurrency actually sequentially adds jobs to self-hosted runner.
> ci: remove concurrency

- charts/lnd/charts/loop/Chart.yaml
- charts/lnd/charts/loop/templates/statefulset.yaml
- charts/lnd/charts/loop/values.yaml
updating Loop to the latest in  https://hub.docker.com/r/lightninglabs/loop/tags
Does not make P2TR available yet as `loopd` needs to run with the `--experimental` flag 
(not present in the dockerfile), see:  https://github.com/lightninglabs/loop/releases/tag/v0.20.0-beta
> chore: update to loop v0.20.1

- charts/specter/Chart.yaml
- charts/specter/values.yaml
Updating to the latest version from https://hub.docker.com/r/lncm/specter-desktop/tags with a lot of bugfixes, features and no breaking changes: https://github.com/cryptoadvance/specter-desktop/releases/tag/v1.10.5
The old vesion is 9months old!
> chore: specter update to v1.10.5

- charts/galoy/templates/cronjob.yaml
- charts/galoy/templates/deployment.yaml
- charts/lnd/Chart.yaml
- charts/lnd/charts/loop/templates/export-secrets-configmap.yaml
- charts/lnd/charts/loop/templates/role.yaml
- charts/lnd/charts/loop/templates/rolebinding.yaml
- charts/lnd/charts/loop/templates/serviceaccount.yaml
- charts/lnd/charts/loop/templates/statefulset.yaml
- charts/lnd/charts/loop/values.yaml
- charts/lnd/charts/loopserver/.helmignore
- charts/lnd/charts/loopserver/Chart.yaml
- charts/lnd/charts/loopserver/templates/_helpers.tpl
- charts/lnd/charts/loopserver/templates/pvc.yml
- charts/lnd/charts/loopserver/templates/service.yaml
- charts/lnd/charts/loopserver/templates/statefulset.yaml
- charts/lnd/charts/loopserver/templates/tests/test-connection.yaml
- charts/lnd/charts/loopserver/values.yaml
- charts/lnd/values.yaml
- ci/testflight/galoy/main.tf
- ci/testflight/rtl/main.tf
- dev/bitcoin/lnd-values.yml
- dev/galoy/main.tf
- images/lnd-sidecar/Dockerfile
This PR adds a new chart called loopserver to be used in dev charts (regtest) and smoketest environments. It also copies the loop macaroon to kubernetes secrets to be consumed by the galoy main backend and cron servers.
> feat: loopserver chart

- charts/galoy/templates/cronjob.yaml
- charts/galoy/templates/deployment.yaml
- ci/testflight/galoy/main.tf
- dev/galoy/main.tf
Test that the env var exists `LND1_LOOP_MACAROON` in the main galoy api
```
APPNAME=api; \
POD=$(k get pod -A -l app=$APPNAME -o jsonpath="{.items[0].metadata.name}"); \
NS=$(k get pod -A -l app=$APPNAME -o jsonpath="{.items[0].metadata.namespace}"); \
k -n $NS describe pod $POD | grep LND1_LOOP_MACAROON;
```
Result should be
```
LND1_LOOP_MACAROON:       <set to the key 'loop_macaroon_base64' in secret 'lnd1-loop-credentials'>  Optional: false
```
> feat: add loop env vars to galoy deployment

- charts/bitcoind/values.yaml
associated PR on galoy: https://github.com/GaloyMoney/galoy/pull/1631
> chore: update bitcoind to v23

- charts/lnd/charts/lndmon/Chart.yaml
- charts/lnd/charts/lndmon/templates/deployment.yaml
- charts/lnd/charts/lndmon/values.yaml
Fixing the errors:
```
Lndmon exiting with error: WalletCollector ListUnspent failed with: invalid utxo address type 4
```
by updating the 2 years old lndmon version (no P2TR support) to the latest https://hub.docker.com/layers/lightninglabs/lndmon/v0.2.1/images/sha256-131497041d6bbf1b164062162c31068dd0dbf8f4bbb065bb44fcadecc5ef52e0?context=explore
Tested the new version locally with taproot addresses on regtest by running:
```
kubectl -n galoy-dev-bitcoin exec bitcoind-0 -- bitcoin-cli createwallet default
kubectl -n galoy-dev-bitcoin exec bitcoind-0 -- bitcoin-cli generatetoaddress 1 $(kubectl -n  galoy-dev-bitcoin exec -it lnd1-0 -c lnd -- lncli -n regtest newaddress p2tr | jq -r .address)
kubectl -n galoy-dev-bitcoin exec bitcoind-0 -- bitcoin-cli -generate 106
```
The `/health` …
> Lndmon update to support Taproot addresses

- ci/tasks/specter-smoketest.sh
- removes the `--location` redirect option from the smoketest.
> fix(spectre): remove '--location' redirect option

- ci/tasks/admin-panel-smoketest.sh
- ci/tasks/dealer-smoketest.sh
- ci/tasks/galoy-auth-smoketest.sh
- ci/tasks/galoy-pay-smoketest.sh
- ci/tasks/specter-smoketest.sh
- ci/tasks/web-wallet-smoketest.sh
- add `-f` option to curl requests to address non-zero exit code of non-200 and non-201 requests.
> fix: add '-f' option to curl requests

- ci/tasks/lnd-smoketest.sh
- ci/tasks/rtl-smoketest.sh
- ci/tasks/web-wallet-smoketest.sh
Originally raised this on the wrong repo here https://github.com/GaloyMoney/galoy-deployments/pull/2181.  Some of the changes don't seem to have been synced by vendir 
The following file is out of sync (curl command is different)
modules/services/auth/vendor/galoy-auth/ci/tasks/galoy-auth-smoketest.sh
The following file has not been deleted but isn't present in charts
modules/services/client-addons/vendor/guatt-web-wallet/ci/tasks/guatt-web-wallet-smoketest.sh
> chore: smoketests should fail when response is non 200

- charts/lnd/Chart.lock
Fixes https://github.com/GaloyMoney/charts/issues/1667
Rollout should be LND no-op.
> fix: lnd chart.lock didn't contain loopserver

- charts/dealer/Chart.lock
Syncs Chart.lock with Chart.yaml, must be a No OP rollout.
Similar to https://github.com/GaloyMoney/charts/pull/1668
> fix: remove postgresql from dealer chart.lock

- dev/README.md
- dev/galoy/galoy-values.yml
related to  the changes in #1389
fixes #1683  
The test output is now:
```
$ curl -k 'https://localhost:8080/graphql' -H 'Content-Type: application/json' -H 'Accept: application/json' --data-binary '{"query":"mutation login($input: UserLoginInput!) { userLogin(input: $input) { authToken } }","variables":{"input":{"phone":"+59981730222","code":"111111"}}}'
{"errors":[{"message":"missing key for twilio","locations":[{"line":1,"column":43}],"path":["userLogin"],"code":"INTERNAL_SERVER_ERROR"}],"data":null}
```
Ingress works and will deal with Twilio in a later change.
> fix: add galoy api ingress and use https test in dev

- charts/bitcoind/templates/statefulset.yaml
Just a small error I've noticed. The context is wrong thus helm would fail when supplying this with a values file.
> fix: helm context for bitcoind prometheus port

- charts/galoy/templates/api-ingress.yaml
@daviroo 
I tested in my local charts dev environment and it appears to have deployed nginx successfully. I also tested a simple subscription graphql query in the playground and it all worked. I am not quite sure how to check the nginx logs to see if the errors are gone.
```
nick@nuc:~/code/charts/dev$ kubectl -n galoy-dev-galoy describe ingress
Name:             api
Labels:           app=api
app.kubernetes.io/managed-by=Helm
chart=galoy-0.5.15-dev
release=galoy
Namespace:        galoy-dev-galoy
Address:          10.43.31.17
Ingress Class:    <none>
Default backend:  <default>
TLS:
api-ingress-tls terminates localhost
Rules:
Host        Path  Backends
----        ----  --------
localhost   
/   api:4002 (10.42.0.31:4002,10.42.0.36:4002)
Annotations:  cert-manager.io/cluster-issuer: …
```
> fix: nginx websocket connections

- charts/admin-panel/templates/ingress.yaml
- charts/bitcoind/templates/ingress.yaml
- charts/galoy-auth/templates/ingress.yaml
- charts/galoy-pay/templates/ingress.yaml
- charts/galoy/charts/price/templates/ingress.yaml
- charts/galoy/templates/admin-ingress.yaml
- charts/galoy/templates/api-ingress.yaml
- charts/lnd/charts/lndmon/templates/ingress.yaml
- charts/specter/templates/ingress.yaml
- charts/web-wallet/templates/ingress.yaml
`kubernetes.io/ingress.class` is now a deprecated annotation: https://kubernetes.io/docs/concepts/services-networking/ingress/#deprecated-annotation
NGINX Ingress Controller already works with this newer spec, hence updating all our Ingresses.
> chore: use ingressClassName instead of annotation to specify ingress

- charts/lnd/charts/loop/templates/statefulset.yaml
- dev/galoy/galoy-regtest-values.yml
- dev/galoy/galoy-signet-values.yml
This PR adds a flag for `--tlsextradomain` to the loop chart that points to loops kubernetes dns
> fix: swap tls extra domain

- ci/pipeline-fragments.lib.yml
- ci/pipeline.yml
- ci/testflight/galoy-deps/main.tf
- ci/values.yml
Using the addons slack for galoy-deps pipeline notifications for now until credential provisioning is blocked. Will replace it in a subsequent PR.
> chore: add galoy-deps testflight

- charts/lnd/Chart.yaml
- charts/lnd/values.yaml
- images/lnd-sidecar/Dockerfile
There are no breaking changes, but a few Taproot related bugs are fixed: https://github.com/lightningnetwork/lnd/blob/v0-15-3-branch/docs/release-notes/release-notes-0.15.3.md
> chore: update lnd docker images to v0.15.3-beta

- charts/galoy/templates/api-ingress.yaml
I found some docs on websockets config for kubernetes nginx - it says we should have a higher value for some configs for proxy for websockets.
https://kubernetes.github.io/ingress-nginx/user-guide/miscellaneous/#websockets
> chore: Increased proxy timeouts for websockets

- charts/galoy/templates/api-ingress.yaml
I can see in the logs that we are actually rate limiting based on number of connections coming from an IP.  I've doubled it for now to see what effect it will have (previously 40 now 80).  This doesn't effect the other rate limits we have in effect.
> chore: Increased connections limit for api ingress

- charts/galoy/templates/api-deployment.yaml
As part of #1389 , the mount path for the service account was set to `/tmp` which changed the `/tmp`'s permissions and made it a readonly path. This PR mounts the service account a level deeper to remedy this issue.
> fix: mount svc account in a subpath under /tmp

- dev/bitcoin/main.tf
- dev/bitcoin/rtl.tf
Adding RTL to the local dev deployment.
To access RTL on the local regtest:
```
env=galoy-dev
k -n ${env}-bitcoin get secrets rtl-pass -o jsonpath='{.data.password}' | base64 -d
k -n ${env}-bitcoin port-forward  $(kubectl get pods -A | grep rtl | awk '{print $2}')  3000:3000
```
Next step is to update update to the [latest version](https://hub.docker.com/layers/shahanafarooqui/rtl/0.13.1/images/sha256-1d2892e29b5ccc4e9768ce0e7764bc9a1fd46c82d02131204f22a6aa239e106b?context=explore),but it doesn't work yet out of the box due to configuration changes.
> feat: add RTL to the dev setup

- ci/pipeline.yml
- ci/tasks/galoy-deps-smoketest.sh
- ci/testflight/galoy-deps/galoy-deps-values.yml.tmpl
- ci/testflight/galoy-deps/main.tf
This PR removes the newly introduce kubectl plugin, and moves the topic creation to the smoketest script. A new watchNamespaces field needs to be set for the helm installation because the topic is being created in the smoketest namespace.
> refactor: galoy deps smoketest

- charts/lnd/Chart.yaml
- charts/lnd/values.yaml
- images/lnd-sidecar/Dockerfile
Preemptive draft to rerun the tests as soon as the new LND release image becomes available at https://hub.docker.com/r/lightninglabs/lnd/tags.
> chore: update lnd docker images to v0.15.4-beta

- ci/tasks/galoy-deps-smoketest.sh
It looks like underscores are not allowed in the names of a kafka topic
> ci: fix kafka topic name in smoketest script

- charts/galoy-deps/Chart.lock
- charts/galoy-deps/Chart.yaml
- charts/galoy-deps/templates/kafka-cluster.yaml
- charts/galoy-deps/values.yaml
- ci/testflight/galoy-deps/main.tf
This PR also overrides the subchart names so that the resources' names are less verbose
> refactor: allow dependencies to be disabled in deps chart

- dev/galoy-deps/kafka.tf
- dev/galoy-deps/kubemonkey.tf
The dev smoketests have been failing because a race condition was introduced with the addition of the deps module. 
The problem is that we install the same chart - the deps chart - multiple times in the form of separate helm releases, each time with only one dependency chart enabled out of all. Terraform attempts these installations in parallel, but they all try to use the same directory to download the dependency charts to, leading to a race condition. Ordering the installation of the different helm releases within the deps module will fix the issue, with the tradeoff of slower test times.
Edit: The smoketest is still failing, but for a different reason now - the otel installation is in an in-between state: it's still present in 'galoy-infra/services' , but we have also added it to deps. …
> ci: fix dev smoketest by ordering deps installations

- charts/lnd/Chart.lock
- charts/lnd/Chart.yaml
- charts/lnd/templates/statefulset.yaml
- charts/lnd/values.yaml
- ci/testflight/lnd/main.tf
- dev/bitcoin/lnd1.tf
LND on postgres is far from production ready. We want to keep the chart clean and only allow configurations that run well in prod, so this PR removes postgres support from the chart.
> chore!: remove pg from lnd

- charts/rtl/Chart.yaml
- charts/rtl/templates/configmap_and_secret.yaml
- charts/rtl/templates/deployment.yaml
- charts/rtl/values.yaml
This updates the rtl chart to the latest version. It needed some changes since newer rtl versions need write-access to the config file.
Which is why I added an init-container which copies over the configuration and sets write permissions for the node-user.
With this the folder /RTL/data will hold the config, lnd-macaroons, lnd-channelbackups & lnd logs.
> chore: update rtl to v0.13.3

- ci/testflight/galoy-deps/main.tf
- ci/testflight/galoy-deps/testflight-values.yml.tmpl
v1.5.2 of the kubemoney chart [removed](https://github.com/asobti/kube-monkey/pull/244) the option to disable rbac, and so testflight fails due to the clash with clusterwide resources from the staging deployment of kubemonkey.
Overriding the fullname with the testflight namespace var will make the clusterwide resources in testflight also unique, fixing the problem.
> ci: use unique name for kubemonkey in testflight

- charts/lnd/values.yaml
- images/lnd-sidecar/Dockerfile
Update to the latest lnd version.
Before merge check tests are passing https://github.com/GaloyMoney/galoy/pull/2199
> chore: update lnd version to v0.15.5-beta

- charts/galoy-deps/values.yaml
The upgrade to 0.47 uses pod ip instead of 0.0.0.0 due to security reasons and thus we should also make the switch to follow best practices.
> chore: use pod ip instead of 0.0.0.0 in otel

- charts/galoy/values.yaml
- dev/galoy/galoy-regtest-values.yml
- dev/galoy/galoy-signet-values.yml
- dev/galoy/main.tf
- dev/galoy/postgresql-values.yml
The Oathkeeper changes are based on:
https://github.com/GaloyMoney/galoy/pull/2103/files#diff-f2d3bed1938639bd048c1629be6fe575621bc4eb0cef967ab52d10f6ca96369e
Kratos:
https://github.com/GaloyMoney/galoy/blob/6f3bcdbb4bc24beb3546a5ade90a5384cc707072/dev/ory/kratos.yml
except:
`schemas`
`dsn`
A new postgresql instance is added to stand up before kratos and the `dsn` is configured accordingly.
> chore: add the kratos and oathkeeper config to the default values

- ci/testflight/galoy/testflight-values.yml
only changing the dsn value for the galoy-testflight
> fix: don't connect to postgres in galoy-testflight

- charts/galoy-pay/templates/ingress.yaml
Referring to the config at https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors
>To enable Cross-Origin Resource Sharing (CORS) in an Ingress rule, add the annotation nginx.ingress.kubernetes.io/enable-cors: "true". This will add a section in the server location enabling this functionality.
>CORS can be controlled with the following annotations:
nginx.ingress.kubernetes.io/cors-allow-methods: Controls which methods are accepted.
This is a multi-valued field, separated by ',' and accepts only letters (upper and lower case).
Default: GET, PUT, POST, DELETE, PATCH, OPTIONS
Example: nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS"
>nginx.ingress.kubernetes.io/cors-allow-origin: Controls what's the accepted Origin for CORS. …
> chore: allow GET calls to galoy-pay for ln address

- charts/galoy/values.yaml
stops testflight using the hardcoded dev namespace for kratos
the port 80 is used as implied in http://
> chore: set the kratos endpoints without namespace

- ci/testflight/galoy/main.tf
- ci/testflight/galoy/testflight-values.yml.tmpl
- dev/galoy/galoy-values.yml.tmpl
- dev/galoy/main.tf
To avoid the possibility of kratos connecting to an other existing postgres instance.
Related to #2626
The same changes are done for dev as for testflight.
> chore: specify the namespace for the kratos pg

- ci/tasks/galoy-smoketest.sh
Deactivating the authenticated smoketests due to the inconsistent results on testflight.
> fix: remove authenticated smoketests

- charts/galoy/values.yaml
- dev/README.md
NOT to be merged until we check metrics on how many legacy jwt users are left. The majority of legacy jwt users have been notified
To be merged with https://github.com/GaloyMoney/galoy/pull/2420
> chore: remove legacy jwt config

- charts/monitoring/Chart.lock
- charts/monitoring/Chart.yaml
Seems like prometheus chart rolled out a change with a bug which is causing the configmap reload container to fail with `unknown long flag '--volume-dir'`. Will wait for them to issue a fix, and rollback to the older version until then.
> revert: prometheus chart upgrade #2758

- charts/monitoring/values.yaml
The dealer scrape job is timing out and that's why there are no metrics being collected by prometheus
> chore: bump dealer scrape job timeout

- charts/galoy/values.yaml
This PR fixes the oathkeeper cookie rules. No need to check the cookie on the `/auth/login` or `logout` routes. Without this rule it falsey checks any cookie (_ga cookies) and returns 401.
See related PR comment https://github.com/GaloyMoney/galoy-deployments/pull/3292#issue-1636753015
> fix: oathkeeper cookie rules

- ci/tasks/galoy-deps-smoketest.sh
Attempt to fix failing smoketest where kubectl cannot find the resources that we're trying to wait upon
> ci: add sleep to deps smoketest

- charts/galoy/charts/price/templates/history-cronjob.yaml
- charts/galoy/templates/balance-notification-cronjob.yaml
- charts/galoy/templates/galoy-cronjob.yaml
- charts/galoy/templates/mongo-backup-cronjob.yaml
`batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob`
> chore: upgrade cronjob api version

- charts/bria/templates/bria-api-svc.yaml
- charts/bria/values.yaml
for GKE usage from bastion.
```yaml
api:
service:
type: LoadBalancer
staticIp: 10.1.2.1
annotations:
networking.gke.io/load-balancer-type: "Internal"
```
> feat: add static ip for bria api

- charts/galoy/templates/api-ingress.yaml
I think this should fix the 502 intermittent errors. I tested it in my local dev chart environment by force deleting the galoy api pod and running a curl on a loop (test script below). Before the nginx retry settings were applied I would get a lot of 502/503 errors when one pod was down and one pod was up. After the retry settings were applied I did not get any errors.
ping-502.sh 
```sh
#!/bin/bash
for i in {1..5000}
do
response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:4002/graphql)
if [ $response -eq 502 ]
then
echo "502 error detected on request $i"
else
echo "Request $i successful, response code: $response"
fi
sleep 0.4
done
```
> fix: 502 intermittent errors

- charts/galoy/values.yaml
The defaults are:
```
`{"failureThreshold":5,"initialDelaySeconds":5,"periodSeconds":10}`
```
https://github.com/ory/k8s/blob/7f848abc734852ae2a26d1898ca9f4d1fc2ccc04/helm/charts/kratos/README.md?plain=1#L28
> chore: decrease kratos livenessProbe periodSeconds

- charts/galoy/values.yaml
Mirrors the changes in:  https://github.com/GaloyMoney/galoy/pull/2575
> chore: remove legacy header from oathkeeper config

- charts/fulcrum/values.yaml
Limiting the load fulcrum can exert on bitcoind with settings from:
https://github.com/cculianu/Fulcrum/blob/master/doc/fulcrum-example-config.conf
```
#
#
#
#
#
#
#
#
#bitcoind_throttle = 50 20 5
```
> chore: limit the bitcoind load of fulcrum

- charts/bitcoind/templates/configmap.yaml
- dev/bitcoin/bitcoind-regtest-values.yml
chatGPT result on why:
`dbcache: 2600`
is converted to:
`dbcache=%!{float64=2600}`
with the current config?
>The error you're seeing is because you're trying to print a float64 type value with printf "%s=%s", which expects string arguments. The printf function in Go (and in this case, Go templating language which Helm uses) expects you to provide a format specifier that matches the type of the variable you're trying to print.
>The %s format specifier is used for strings. When you try to print a float64 using %s, it doesn't know how to convert it and hence the output dbcache=%!{float64=2600}.
>To fix this, you should use the %v format specifier, which is a generic format specifier that can print any type in its default format. 
Tested with the integer values quoted and unquoted as well - …
> fix: bitcoindCustomConfig parsing

- charts/bitcoind/templates/statefulset.yaml
The predefined annotations including the configmap checksum were not applied if `.Values.podAnnotations` was empty.
> fix: always use bitcoind configmap checksum

- .github/workflows/dev-smoketest.yaml
as configured concurrency cancels the previous workflow of a branch if a new commit is pushed
TODO: cancel the workflow when the PR is closed can use this third party action:
https://github.com/marketplace/actions/cancel-workflow-action
> build: add concurrency to dev-smoketest action

- ci/testflight/galoy-pay/main.tf
- ci/testflight/galoy-pay/testflight-values.yml.tmpl
Pay testflight was actually not working because it didn't know the staging api hostname. #3530 (wip) will fix the smoketest so this is actually being tested.
> ci(testflight): fix pay testflight

- dev/Makefile
add the command in `./dev` :
```
make helm-dep-updates
```
to update all charts with dependencies.
The terraform `dependency_update  = true` is only meant for local cache and has no effect on the persisted helm chart files.
> build: add helm-dep-updates to Makefile

- ci/tasks/dealer-smoketest.sh
Making the dealer smoketest a dummy since dealer is going to be deprecated soon
> ci: always exit with 0 in dealer smoketest

- ci/tasks/dev-smoketest-settings.sh
The `dev-smoketest-settings.sh` script creates files as root and therefore the github actions, that run as a service account, do not have permissions to write over those files.
> ci(dev): fix dev smoketest permission issue

- ci/pipeline.yml
- ci/values.yml
PR opened successfully when repiped: https://github.com/GaloyMoney/charts/pull/3773
needs repipe again when merged.
> ci: add  job bump-kafka-connect-image-in-chart

- ci/tasks/kafka-connect-smoketest.sh
To allow more time for the kafka-connect pod to be ready when it is deployed first.
> ci: add sleep to kafka-connect smoketest

- charts/kafka-connect/templates/kafka-connect.yaml
- charts/kafka-connect/values.yaml
Makes it possible to pass the mongo-connection-uri to the kafka-connect pod as a file from a secret.
> chore: add FileConfigProvider, add secretMounts

- charts/galoy/values.yaml
- dev/README.md
I want the token to refresh when it's been used, instead of doing it from the cronjob. 2 reasons:
- having the refresh in the cronjob had lead to multiple incident in the past, where the cronjob was failing in multiple ways
- if a device is not been used, in the current design, the token would still be valid even years later. with a "refresh only when the token is used", token that are no longer used would, after some time, be invalid. user would need to log back in
for this new mode of operation to work, we need to make the token valid for longer. I'm suggesting 13 months, and the token expiration would be automatically renew when its validity is less than 12 months.
> chore: making the session token valid for longer

- charts/galoy/templates/galoy-cronjob.yaml
Fix `NoConnectionToDealerError` https://ui.honeycomb.io/galoy/datasets/galoy-bbw/result/zLwLiMEBkcF
> fix: cronjob dealer connection error

- charts/bria/Chart.lock
- charts/bria/Chart.yaml
It's not being used anywhere in the bria chart.
> refactor: remove common chart dep from bria

- charts/galoy/templates/admin-ingress.yaml
This is a hacky fix for forwarding the requests made to the admin ingress to the correct path on the decisions api endpoint. Because oathkeeper uses cues from the nginx headers that we set via the auth-snippet annotation, it sends the requests to the /graphql path on the decisions api - which then gets matched against the public api rules.
> fix: admin oathkeeper request fwd

- charts/galoy/Chart.yaml
- charts/galoy/values.yaml
Dear Galoy team,
In my infra I am already running the hydra stack in its own namespace. I think making it an optional dependency allows for greater flexibility downstream.
Thank you,
Zoop
> chore: make hydra dependency optional

- charts/galoy/charts/price/templates/history-cronjob.yaml
- charts/galoy/templates/galoy-cronjob.yaml
- charts/galoy/templates/mongo-backup-cronjob.yaml
This will add the "app" label to the pods created by the cronjobs.
This way it's easier to target them for network policies and make them more visible in observational tools.
> chore: add app labels to cronjobs jobTemplate

- charts/galoy/templates/api-deployment.yaml
- charts/galoy/values.yaml
Adds capability to set an environment variable that lets any phone number login. This is an insecure flag. It's disabled by default.
> chore: unsecure login code in galoy chart

- charts/fulcrum/Chart.yaml
- charts/fulcrum/values.yaml
The Dockerhub release is manually triggered for now: https://github.com/cculianu/Fulcrum/issues/143
> chore: update fulcrum to v1.9.2

- dev/galoy/Tiltfile
Adding notifications pod to the list of pods we ignore in tilt ci as it hasn't been setup in the dev workflow yet.
> ci(dev): ignore notifications pod readiness

- charts/galoy/templates/_helpers.tpl
This PR adds an env var to the LND env var helper function to store the lnd credentials checksum. This is to allow the core pods to be restarted whenever the credentials change, without having to manually restart them.
> chore: add cred checksum as env var to core pods

- charts/api-dashboard/values.yaml
Reverts GaloyMoney/charts#5644
Reverting due to issue with scopes migration
> revert: "chore(deps): bump-dashboard-image-a19f31f"

- charts/galoy-deps/values.yaml
We have about 180k events for this per day
> chore: filter out query planning spans from router

- charts/galoy/templates/api-ingress.yaml
I used this PR https://github.com/GaloyMoney/charts/pull/2487 as a base.
I think the default values are enough but maybe it would be better to do another review https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors
> chore(galoy-api): enable cors

- ci/tasks/galoy-deps-smoketest.sh
> fix: kafkacat is called with kcat, shellcheck formatting

- charts/galoy/templates/api-ingress.yaml
allowing the header oauth2-token to fix the invoice generation error when logged in to the PoS
> fix: api ingress cors allow header oauth2-token

- charts/galoy-deps/values.yaml
Need to explicitly define the image we want to use now. Previously otel was using the contrib image but there's a newer k8s specific image they recommend - https://github.com/open-telemetry/opentelemetry-helm-charts/blob/main/charts/opentelemetry-collector/UPGRADING.md#0880-to-0890
> fix: otel upgrade

- charts/lnd/values.yaml
bitcoin.active is depreacated now as its the only chain supported - https://docs.lightning.engineering/lightning-network-tools/lnd/lnd.conf
> chore: remove deprecated lnd config field

- charts/galoy-deps/values.yaml
This PR addresses the error "references processor 'memory_limiter' which is not configured". The issue arose from a change in how null values are interpreted for the memory_limiter property. Previously, setting it to null would use the default value. However, there was an inconsistency where some queries would disable the memory limiter when set to null, while others would use the default value.
To resolve this, the PR explicitly specifies the default value for the `memory_limiter` property. This approach ensures consistent behavior across all queries and serves as a potential fix for the error.
Reference: 
https://github.com/open-telemetry/opentelemetry-helm-charts/issues/1272
https://github.com/open-telemetry/opentelemetry-helm-charts/pull/1275
> fix(otel): Explicitly specify memory_limiter value

- charts/bitcoind/templates/statefulset.yaml
- charts/bitcoind/values.yaml
- images/chain-dl/Dockerfile
Merge before or after deploy https://github.com/GaloyMoney/charts/pull/6678 to prod
> chore: update bitcoind to v27.0

- .github/workflows/tilt.yaml
matching the k3s version used in dev since https://github.com/GaloyMoney/charts/pull/7091
> ci: match tilt test k3s version with dev and prod

- charts/galoy-deps/values.yaml
Fixing the error leading to not receiving memory and cpu usage metrics.
The kubestats endpoint has a self-signed certificate which fails the verification by the otel pod.
The solution is recommended here: https://github.com/kubernetes/kubernetes/issues/125956
Related docs:
https://github.com/open-telemetry/opentelemetry-collector/blob/main/config/configtls/README.md
> fix: do not verify kubeletstats endpoint cert

- charts/galoy/Chart.lock
- charts/galoy/Chart.yaml
- charts/voucher/Chart.lock
- charts/voucher/Chart.yaml
This PR updates Postgres Helm Chart Dependencies PG11 -> PG14 for voucher and galoy in blink monorepo.
> chore(deps): Update postgresql helm chart in Galoy and Voucher

- charts/bria/Chart.lock
- charts/bria/Chart.yaml
This PR updates Postgres Helm Chart Dependencies PG11 -> PG14.
> chore(deps): Update postgresql helm chart in Bria

- charts/fulcrum/Chart.yaml
- charts/fulcrum/values.yaml
Config details from: https://github.com/cculianu/Fulcrum/blob/master/doc/fulcrum-example-config.conf
`max_subs_per_ip = 1000000` does allow to sync wallets tracking more than the default 75000 addresses.
The global `max_subs` limit  (DEFAULT: 10M) still applies.
```
#
#
#
#max_subs = 10000000
#
#
#
#max_subs_per_ip = 75000
```
`utxo_cache` was called `fast-sync` previously.
It only affects the initial sync of fulcrum:
```
#-------------------------------------------------------------------------------
#-------------------------------------------------------------------------------
#
#
#utxo_cache = 0
```
> chore: update fulcrum and adapt config to large wallets

- ci/pipeline-fragments.lib.yml
- ci/pipeline.yml
This is the current state of the ci pipeline updated with:
```
ci/repipe helm-charts
```
> ci: deactivate blocked slack notifications

- charts/fulcrum/templates/configmap.yaml
- charts/fulcrum/templates/statefulset.yaml
- charts/fulcrum/values.yaml
- Enable admin to allow manual stops
- Update initialDelaySeconds in livenessProbe to allow initial sync with current network conditions
- Add terminationGracePeriodSeconds to use 10 mins (similar to lnd) to avoid db corruption
> chore: update fulcrum chart to enable admin and longer termination grace period

- charts/voucher/templates/deployment.yaml
add wait for postgresql init container similar to bria https://github.com/GaloyMoney/charts/blob/main/charts/bria/templates/bria-deployment.yaml#L38 to fix a race condition in voucher testflight https://ci.blink.sv/teams/dev/pipelines/helm-charts/jobs/voucher-testflight/builds/57 (I tested in testflight namespace restarting the voucher pod after postgresql pod is ready and all worked correctly)
> fix(voucher): add wait-for-postgresql init container

- charts/bria/Chart.lock
- charts/bria/Chart.yaml
Reverts GaloyMoney/charts#7531
Failing testflight with a postgres related error:
```
k -n bria-testflight-a1b4894 logs  bria-6f97456c99-qswcg
Defaulted container "bria" out of: bria, wait-for-postgresql (init)
Sending traces to http://localhost:4317
Starting server processes
Error: while executing migration 20210316025847: error returned from database: function uuid_nil() does not exist
Caused by:
0: error returned from database: function uuid_nil() does not exist
1: function uuid_nil() does not exist
```
> revert: chore(deps): update postgresql helm chart in bria

- charts/galoy-pay/values.yaml
This is the very same as defined in the subchart:
https://github.com/GaloyMoney/charts/blob/main/charts/galoy-pay/charts/galoy-nostr/values.yaml
> chore: make galoy-nostr image configurable in galoy-pay chart

- charts/galoy-pay/values.yaml
This is supporting the blinkbitcoinbot's PR for changing the galoy-nostr image digest.
First we need to change the repository of the image.
This PR does that. The edge-image currently has that sha256 digest.
Pull the image like:
```
docker pull us.gcr.io/galoy-org/blink-nostr:edge
```
See [this PR](https://github.com/GaloyMoney/charts/pull/7627) for an example of the blinbitcoinbot PRs.
> chore: switch to blink-nostr image

- charts/galoy-deps/values.yaml
* `preset` to do most of the job
* Adding additional access right to avoid:
<details>
```
W0429 13:51:26.139100       1 reflector.go:561] k8s.io/client-go@v0.31.3/tools/cache/reflector.go:243: failed to list *v1.Event: events is forbidden: User "system:serviceaccount:galoy-staging-otel:opentelemetry-collector" cannot list resource "events" in AP │
│ E0429 13:51:26.139163       1 reflector.go:158] "Unhandled Error" err="k8s.io/client-go@v0.31.3/tools/cache/reflector.go:243: Failed to watch *v1.Event: failed to list *v1.Event: events is forbidden: User \"system:serviceaccount:galoy-staging-otel:opentelem │
│ 2025-04-29T13:51:33.060Z    info    Traces    {"kind": "exporter", "data_type": "traces", "name": "debug", "resource spans": 1, "spans": 2} …
```
> chore: add k8s_events incl access rights to otel config

- charts/admin-panel/templates/deployment.yaml
- charts/admin-panel/values.yaml
Enables a env-var called USER_ROLE_MAP which passes a json-map which is mapping users to roles from a chart param to a env-var for the admin-panel.
> feat: passthrough USER_ROLE_MAP for admin-panel

- charts/lnd/values.yaml
The lnd-backup image will be bumped to digest:
```
sha256:640b70a2bce4f700bc86183add31de86775687a5548ead0d2e559a5f81a5df88
```
Code diff contained in this image:
https://github.com/blinkbitcoin/charts/compare/c8d61e0...807735b
> chore(deps): bump-lnd-backup-image-807735b

- charts/lnd/values.yaml
The lnd-backup image will be bumped to digest:
```
sha256:0f016fef49c0f3d2d0ac913d71e570e7e35d55eac200d8d1ea227b924e3d2b3f
```
Code diff contained in this image:
https://github.com/blinkbitcoin/charts/compare/807735b...e520967
> chore(deps): bump-lnd-backup-image-e520967

- charts/galoy/values.yaml
- dev/Tiltfile
- flake.nix
We need to switch out the bitnami charts but in the meantime, let's temporally use bitnamylegacy images.
https://github.com/bitnami/containers/issues/83267
Also:
* Adding [k9s](https://k9scli.io/) to the nix available binaries. Quite usefull for dev
* For me, Tilt went in a endless loop because after downloading the chart dependencies. The change in the Tiltfile prevents that by ignoring the directories where helm is downloading dependent charts.
> fix: replace bitnami repo with bitnamilegacy

- ci/testflight/galoy-auth/postgres-testflight-values.yml.tmpl
- ci/testflight/galoy/api-keys-postgresql-values.yml
- ci/testflight/galoy/main.tf
- ci/testflight/galoy/notifications-postgresql-values.yml
- ci/testflight/galoy/postgresql-values.yml
- ci/testflight/galoy/testflight-values.yml
to fix the error in the galoy testflight:
```
ormal   Scheduled  4m10s                default-scheduler  Successfully assigned galoy-testflight-a496c63/api-keys-postgresql-0 to gke-galoy-staging-cl-galoy-staging-n2-49e7cdb5-b7p7
Normal   Pulling    80s (x5 over 4m10s)  kubelet            Pulling image "docker.io/bitnami/postgresql:14.5.0-debian-11-r35"
Warning  Failed     79s (x5 over 4m10s)  kubelet            Failed to pull image "docker.io/bitnami/postgresql:14.5.0-debian-11-r35": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/bitnami/postgresql:14.5.0-debian-11-r35": failed to resolve reference "docker.io/bitnami/postgresql:14.5.0-debian-11-r35": docker.io/bitnami/postgresql:14.5.0-debian-11-r35: not found
Warning  Failed     79s (x5 over 4m10s)  kubelet …
```
> fix(ci): use bitnamilegacy/postgresql images in testflight, match versions

- ci/testflight/galoy/main.tf
Removing the pinned version makes terraform use the latest version.
> fix(ci): use the latest bitnami chart version in testflight

- ci/testflight/galoy/main.tf
Recommended in: https://artifacthub.io/packages/helm/bitnami/postgresql
To fix in testflight:
```
│ Error: could not download chart: invalid_reference: invalid tag
│ 
│   with helm_release.postgresql,
│   on main.tf line 362, in resource "helm_release" "postgresql":
│  362: resource "helm_release" "postgresql" {
```
> fix(ci): use oci registry-1.docker.io bitnamicharts
